services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume:
