# Generated by Django 6.0.4 on 2026-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('graphs', models.TextField(verbose_name='Графики')),
                ('source_data', models.TextField(verbose_name='Исходные данные')),
            ],
            options={
                'verbose_name': 'Архив симуляции',
                'verbose_name_plural': 'Архив симуляций',
                'ordering': ['-date'],
            },
        ),
    ]
