# Generated by Django 6.0.4 on 2026-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_page', models.CharField(choices=[('brake_view', 'Непрерывное интегрирование'), ('brake_form2', 'Пошаговое интегрирование'), ('brake_form3', 'Импорт из файла')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_data', models.TextField()),
                ('force_data', models.TextField(blank=True)),
                ('motion_data', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'История расчёта',
                'verbose_name_plural': 'История расчётов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SimulationArchive',
        ),
    ]
